In [192]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import scipy.optimize as opt

In [193]:
##Importing the data and making the necessary changes : 
columns = ['income', 'age', 'education', 'private-work', 'married', 'capital-gain', 'capital-loss', 'hours-per-week']
data = np.genfromtxt("04-dataset.tsv")

In [194]:

assert data.shape[1] == 8, 'you already ran this cell!'
data = np.concatenate([data, np.ones((data.shape[0], 1))], axis=1)  # add a column of ones
data.shape

(32561, 9)

In [195]:
##Writing the gradient function 
#  weight vector
#X Mapping ,assumption is that mapping will already be there 
#Target values
#Actual Output 

##The name test is very confusing  here .It just means run the model with the weights as given in parameters : 
def test(w,X):
    #print("Inside the test(w,X) function ")
    return(sigmoid(X@w))

##The return of this function will actually return the optimal weights
def train(X,t,a):
    #print("Inside the train function ")
    fprime = gradient
    return opt.fmin_bfgs(  
    f = cost , fprime = fprime , x0=np.random.normal(scale =0.2 ,size =(X.shape[1],)),args=(X,t,a),disp = 0)

def sigmoid(a):
    #print("Inside sigmoid(a) function : ")
    return 1/(1+np.exp(-a))

##SELF SOLUTION ###
###################
def cost(w,X,t,a):
    #print("Inside cost(w,X,t,a) function : the shape of the arguments are :",np.shape(X))
    #binary cross-entropy loss is 

    y = test(w,X)
    #Below was not actually required ,because sigmoid anyway squashes a value between 0 and 1.But still following 
    #along the lecture code
    mask = (y>0) & (y<1)
    t = t[mask]
    y = y[mask]
    
    
    #regularisation and L2 penalty
    #l2 = (w@w)*a/2
    l2 = (w**2).sum() * a / 2
    likelihood = t@np.log(y) +(1-t)@np.log(1-y)
    cost_function = -likelihood + l2
    return cost_function 
    
#This would go as an input to scipy.optimize.fmin_bfgs
##SELF SOLUTION ###
###################

def gradient(w,X,t,a): 
    y = sigmoid(X@w)
    #print("In gradient() , shape of x is :",np.shape(np.transpose(X)) ,"and w  is : ",np.shape((np.transpose(X)@(y-t)).sum(axis=0) + a *w))
    #print("And the value of w is : ",(np.transpose(X)@(y-t)).sum(axis=0) + a *w) 
    #return (X * (y - t)[:, None]).sum(axis=0) + a * w
    return ((np.transpose(X)@(y-t)) + a *w)


In [196]:
##Running the model : 
##Taking 80% as the Training data and 20% Testing Data.
N = np.shape(data)[0] #No. of rows in the data
num_train = int(N*0.8) #26048
num_test = int(N*0.2)  #6512

##Normalising the data : 
data_NORMALISED = data[:,1:]/data[:,1:].sum(axis=0,keepdims =True)

x_train = data_NORMALISED[:num_train ,1:]
x_test = data_NORMALISED[:num_test,1:]


##data is used below because data_NORMALISED has no income field, see the slicing above.
y_train = data[:num_train, 0]
y_test = data[:num_test, 0]

In [199]:
##Graph between analytical gradient and numerical gradient left for now . 
##See this space for the second iteration . 

In [201]:
#Running the code : 
w_train = train(x_train, y_train, 1e-1) #tweak regularisation parameter so weights are not big
y_guess = test(w_train, x_test)
#print(y_guess)
#print(w_train)

[0.50000141 0.49995336 0.49993282 ... 0.49992722 0.49995287 0.49994228]
[-1.79389055 -2.25881082 -0.51415345  3.17457225  0.26087634 -1.84469167
 -2.08285924]


In [277]:
##Writing the Confusion Matrix 
##We will use a threshold of 0.5 for the data to be predicted as 1 , and 0 otherwise : 
def confusion_matrix(y_true, y_pred): 
    y_pred[y_pred >= 0.5] = 1
    y_pred[y_pred < 0.5] = 0
    true_positives = np.sum(np.array(y_pred==1) & np.array(y_pred ==y_true))
    true_negatives = np.sum(np.array(y_pred==0) & np.array(y_pred ==y_true))
    false_positives = np.sum(np.array(y_pred==1) & np.array(y_pred !=y_true))
    false_negatives = np.sum(np.array(y_pred==0) & np.array(y_pred !=y_true))
    return np.array([[true_negatives ,false_negatives],[false_positives,true_positives]])
    
    
def accuracy(confusion_matrix): 
    total_correct = confusion_matrix[0][0]+confusion_matrix[1][1]
    return  total_correct/np.sum(confusion_matrix)
    


In [278]:
#Calculating the accuracy :
cm = confusion_matrix(y_test , y_guess)
result = accuracy(cm)

In [279]:
print(result)

0.7893120393120393


In [263]:
y_guess = y_pred
y_pred[y_pred >= 0.5] = 1
y_pred[y_pred < 0.5] = 0
print(y_pred==1)
#print(y_test == y_guess)
#print(y_pred==1 &  y_pred == y_test)

[ True False False ... False False False]


In [276]:
np.array(y_pred==1) & np.array(y_pred == y_test)
#type(y_pred==1)
#y_pred == y_test

array([False, False, False, ..., False, False, False])

In [274]:
np.array([True ,False]) & np.array([True, True])

array([ True, False])

In [246]:
y = np.array([0,1,2,4,5,6,7,8])
# if(y>4):
#     print("Hello world")
# y[(y>4)] =1
# print(y)
a = np.array([[1,2],[3,5]])
print(a[0][1])
# print(np.sum(a))


# print(2!=4)


2


In [247]:
y = np.array([0,1,2,4,5,6,7,8])
np.sum(y>7)

1